### ISSUE TITLE
Codable Support

### ISSUE THREAD

**Issue by sena-mike** [Outdooractive/gis-tools#8]
Was there an intentional decision to avoid using `Codable` for the GeoJSON support?

**Comment by trasch** [comment]
No special reason apart from that we never needed it. 

The basic idea of this GeoJSON implementation is far older than the repository and there was no `Codable` support in Swift at that time (and then it wasn't great for a while).

I will think about adding a compatibility layer as we have elsewhere. Do you have anything special in mind?

**Comment by sena-mike** [comment]
I see, makes sense given the history. It's gotten pretty good but there may still be challenges with things like `foreignMembers` where you still want a generic object. Some other projects use a `Coddle` `JSON` enum that looks something like:

```swift
public enum JSON: Hashable, Sendable {
    case string(String)
    case number(Double)
    case boolean(Bool)
    case array([JSON])
    case object([String: JSON])
    case null
}
```

That could be an option for the arbitrary payloads.

**Comment by trasch** [comment]
I have now added `Codable` support to all GeoJSON types, plus a helper for loading unknown GeoJSONs: https://github.com/Outdooractive/gis-tools/releases/tag/0.5.0

In general, `Codable` doesn't work very well with flexible objects like GeoJSON, so I personally don't and wouldn't use it because it IMO complicates things... I would recommend using one of the initializers inherited from `GeoJsonReadable`. I myself usually use `FeatureCollection` for unknown inputs, as this will wrap any object into a well known structure and that makes it easier to work with.

But if you want, then you can now use something like this:
```
let someGeoJson = GeoJsonReader.geoJsonFrom(jsonString: "{\"type\":\"Point\",\"coordinates\":[100.0,0.0]}")!
switch someGeoJson.type {
case .point: ...
}
// or
switch someGeoJson {
case let point as Point: ...
}
```

**Comment by trasch** [comment]
@sena-mike Does this work for you? I'm also currently (finally) busy with writing the documentation, so if there is anything that you want documented, then add it here: #10 :)

**Comment by sena-mike** [comment]
Yea thanks for the Coddle support, totally agree it's a bit lacking in the flexible object department.
